name: Publish
on:
  - workflow_dispatch


concurrency:
  group: "publish"
  cancel-in-progress: false


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Gradle Assemble
        run: ./gradlew assemble --info -S --show-version


  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Gradle Check
        run: ./gradlew check --info -S --show-version


  build-docs:
    name: Build Documentation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Build JavaDoc
        run: ./gradlew javadoc --info -S --show-version

  build-artifact-bundle:
    name: Build Artifact Bundle
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          distribution: "temurin"
          java-version-file: .github/workflows/.java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4

      - name: Build Artifact Bundle
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew --init-script ./.github/init.gradle.kts artifactBundle --info -S --show-version

      - name: Upload Artifact Bundle
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: "artifact-bundle"
          path: "./build/libs/maven-artifact-bundle.tgz"

  central-upload:
    name: Upload to Central Portal
    needs: [build-artifact-bundle, build-docs]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact Bundle
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: "artifact-bundle"
          path: .

      - name: Upload to Central Portal
        uses: TheMrMilchmann/central-portal-actions/upload-deployment@3b930f17b4a03b4e330ec419812ec447e11cafa3 # v0
        with:
          username: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          password: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          bundle: ./maven-artifact-bundle.tgz
          publishing-type: "user-managed"
